### PR TITLE
Edge Cases for Memory Leaks

### PR DESCRIPTION
**Pull request by AlexanderTsarapkine**
Used by lab instructor to "break code"

### CODE REVIEW

**Review by nickchan2 — APPROVED** [review]

**Comment by JZJisawesome** [comment]
Hi, the manifest changes/names look good, but the input isn't valid in certain places and neither is the output.

For example, "DEF x" must be followed by a number **on the same line**, not on the one after.

Additionally, the output does not match what would be expected for the input. "success" is missing in a few places for example.

Once these issues are fixed I'd be happy to merge this PR. Thanks for your contribution!

**Comment by AlexanderTsarapkine** [comment]
Hi, there isn't a requirement for what line the input command components must be on, simply what value follows what kind of command, e.g DEF must be followed by the name and value ( the lab instructor entered these commands in this exact order when I asked him to break my code if this helps as well, and he mentioned this usually causes memory leaks).

I've also only included outputs to commands that require them, for example, I skipped outputting during the END command since it doesn't require an output and the PRT command either outputs the variable that was specified or outputs that that variable does not exist (so no success or failure); hence there's 8 total individual commands and only 7 outputs.

Hope this helps!

**Comment by DanielJPuratich** [comment]
From the project description "The script files will be comprised of statements, one per line, that hold either variable declarations, commands, or desired computations" so it may be worth a Piazza question to clarify what the lab instructor stated.

**Comment by AlexanderTsarapkine** [comment]
Must've missed that, I guess its a bit conflicting when that's how the commands were used on my implementation but I'll update that since it probably doesn't make a difference since the parser implementation demonstrated would be able to handle both cases.

**Pull request merged**
